# Generated by Django 3.2.9 on 2022-05-11 17:59

import base.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentfile',
            name='file',
            field=models.FileField(blank=True, help_text='Максимальный размер файла: 500 МБ. /n Разрешённые типы файлов: txt doc docx xls xlsx pdf png jpg rar zip ppt pptx rtf gif.', null=True, upload_to=base.models.file_directory_path, validators=[django.core.validators.FileExtensionValidator(['pdf'])], verbose_name='Вложения'),
        ),
    ]
