# Generated by Django 3.2.9 on 2022-04-28 13:04

import base.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20220428_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(blank=True, max_length=200, null=True, upload_to=base.models.category_directory_path, verbose_name='Вложения'),
        ),
        migrations.DeleteModel(
            name='File',
        ),
    ]
