# Generated by Django 3.2.9 on 2022-04-28 14:28

import base.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_auto_20220428_1604'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название файла')),
                ('file', models.FileField(blank=True, max_length=200, null=True, upload_to=base.models.category_directory_path, verbose_name='Вложения')),
            ],
            options={
                'verbose_name': 'Вложение',
                'verbose_name_plural': 'Вложения',
            },
        ),
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=base.models.category_directory_path, verbose_name='Вложения'),
        ),
    ]
