# Generated by Django 3.2.9 on 2022-04-28 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_auto_20220428_1728'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='file',
        ),
        migrations.AddField(
            model_name='document',
            name='file',
            field=models.ManyToManyField(blank=True, to='base.File', verbose_name='Файл'),
        ),
    ]
