# Generated by Django 3.2.9 on 2022-05-04 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_auto_20220428_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Название файла'),
        ),
    ]
