# Generated by Django 3.2.9 on 2022-05-04 12:10

import base.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_file_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=base.models.category_directory_path, verbose_name='Вложения'),
        ),
    ]
