# Generated by Django 3.2.9 on 2022-05-04 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_alter_document_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='base.category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='document',
            name='law',
            field=models.ManyToManyField(blank=True, related_name='laws', to='base.Law', verbose_name='Закон'),
        ),
    ]
