# Generated by Django 3.2.9 on 2022-05-04 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_auto_20220504_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='law',
            field=models.ManyToManyField(blank=True, to='base.Law', verbose_name='Закон'),
        ),
    ]
